### ISSUE TITLE
Question about a repo

### ISSUE THREAD

**Issue by veso266** [sm3ulc/wspr-scripts#1]
Hi this is not an issue but a question about a repository that was deleted but you hopefully still have a copy somewhere
the repository in question is: https://github.com/sergionavarrog/RDSOutput (its a RDS Output plugin for SDR#), that was unfortinaly deleted along with eprsons github account so its gone forever

so I am asking if you maybe at least have a dll somewhere, but if you have code and dll it would be great if you could upload it somewhere

also you commented on its issue in the past: https://webcache.googleusercontent.com/search?q=cache:EMAAv1KgZJYJ:https://github.com/sergionavarrog/RDSOutput/issues/1+&cd=13&hl=sl&ct=clnk&gl=si

so there is maybe still some hope left

Thanks for Anwsering and Best Regards

**Comment by sm3ulc** [comment]
Sorry! Have no files left. Made a misstake and cloned it.

Kind regards,

//David

Den tor 3 maj 2018 13:01veso266 <notifications@github.com> skrev:

**Comment by ghost** [comment]
Hi
I uploaded a new RDSOutput repository here:
https://github.com/bra1z/RDSOutput
Regards

**Comment by veso266** [comment]
Thanks

now if anyone maybe had archived redseaWF from him: https://webcache.googleusercontent.com/search?q=cache:9Dc2IBcYFBUJ:https://github.com/sergionavarrog/redseaWF/blob/master/redseaWF/Form1.resx+&cd=7&hl=sl&ct=clnk&gl=si&client=firefox-b it would be great

google cache didn't capture much interesting stuff unfortionally 
https://webcache.googleusercontent.com/search?q=cache:_RwtI9QBj74J:https://github.com/sergionavarrog/redseaWF/blob/master/appveyor.yml+&cd=5&hl=sl&ct=clnk&gl=si&client=firefox-b


PS: does anyone know how was this supposed to work
I have compiled this for the Net framework 4.6 and it shows in SDRSharp when adding it via this line in plugins.xml
```
<add key="RDS Output" value="SDRSharp.RDSOutput.RDSOutput,SDRSharp.RDSOutput" />
```

but nothing is displayed in the white box where RDS groups should show but RDS is clearly there
![rdsoutputplugin](https://user-images.githubusercontent.com/6347325/39633852-b2bb7fee-4fa8-11e8-8247-2c91e0308a7e.png)

and VS Debugger is not much help eather

**Comment by ghost** [comment]
In RDS Spy program configure menu -> Select RDS Source :
- Connection Type: TCP/IP
- TCP/IP Host:  localhost
- TCP/IP Port:  23

Also I uploaded a new redseaWF repository here:
https://github.com/bra1z/redseaWF

**Comment by veso266** [comment]
Thanks again
it works now
not sure how to use RedSeaWF (how does it get JSON in to itself from redsea?)

**Comment by ghost** [comment]
redseaWF use json.NET library to deal with the JSON stream.
redseaWF repository include in Release folder all files needed to run.
You can also use these files:
https://build.opensuse.org/package/show/home:mnhauke:mingw:win64:sdr/mingw64-redsea
for 64 bits windows.
Look into Helper.cs the StartRedseaProgram function to see how the program write run_redsea.cmd to call the rtl_fm program. Maybe for 64 bits windows you have to use another rtl_fm version.

**Comment by veso266** [comment]
no it works fine I am just using a bit diferent command to read rds out of RDSea and it aphears this cannot read json from it
curl -s http://5.35.250.101:8000/radio700-mpx.flac | flac --totally-silent --ogg -d -c - | redsea

but when changing run_redsea.cmd to this instead of rtl_fm one it doesn't work for some reason

Thanks for Helping
PS: Question about your TMC Location Tables (saw you have slovenian one, are those public or private from TrafficNav (I am looking for those but they would not give them to me)

**Comment by ghost** [comment]
I made a workaround to use it like you want. Just rename or delete run_redsea.cmd and leave the program create a new file. Next time you can modify the file to put another URL if you want.
All my repository tables are from https://gitlab.com/mvglasow/qz. I don't know nothing about what kind of tables are. I just spend a few hours converting from jdbc format to the one used for redsea. I hope will be useful for anyone.

**Comment by veso266** [comment]
works like a charm :smiley:

**Comment by electro-soma** [comment]
I see RDSOutput has disappeared again! If anyone can help me out and provide me with it I would be grateful. Thanks.

**Comment by veso266** [comment]
here ya go :smile: : https://github.com/veso266/RDSOutput
and here is RedSeaWF: https://github.com/veso266/redseaWF

the Onlything that I never downloaded is this: https://github.com/bra1z/redseaTMCmap
he mentioned it here: https://github.com/windytan/redsea/issues/58 but I forgot to try it and now its gone :cry: and needs to be recreated

**Comment by electro-soma** [comment]
You're a star. Cheers! I'm not familiar with building these things but I see the DLL is already in there and the magic line for the Plugin file. I'll see how I get on. 

The reason I was after this is because I've had no luck getting RDS Spy to work with SDR# + MPX Output plugin with the Virtual Audio Drivers. It seems as the though this could do the same thing?

Thanks again and I may be back to pick your brains! ;-)

**Comment by veso266** [comment]
there is one diference :smile: 
if using RDS Spy it will handle RDS stream, extraxt groups from it and display it
while if using this SDR# will extraxt groups from MPX stream and you are essentialy using RDS Spy only for nice RDS Display :smile:  so try to get RDS Spy working because its still sometimes detects PI Codes when SDR# doesn't

do you see the whole MPX stream if you view it with something like MPXTool: http://downloads.dxing.si/download.php?file=SA/MPXTool/MpxTool.2.10.03.DXSW.zip ?

maybe you didn't set your cable to 192khz?

**Comment by electro-soma** [comment]
Over in the Skywaves chatroom I went through the MPX/RDS/SDR# install with a couple of people who have it running succesfully. They looked at my install and they're all baffled as to why it's not working. As am I. The only thing I can think of is Windows 8.1 is running on my Mac. This shouldn't be a problem however as it's not running under a virtual PC, it's running under Bootcamp. 

So basically there is no emulation going on and Windows uses the full hardware without any trickery and no trace of Mac OS.  On boot up I have a choice of OS X or Win 8.1. But maybe there is some low level incompatibility somewhere. I'm not really a Windows person but I do use it for some things and of course it has all the best SDR software.

Anyway, I'll try this out later and report back. Thanks.

**Comment by electro-soma** [comment]
Well it's working :-) But I'm confused! RDS Spy now displays information. That's great. What confuses me is it appears to display exactly what I see in SDR Sharp's RDS display, including any errors. 

So is RDS Spy just displaying the RDS information from SDR Sharp's own RDS software? I was hoping RDS Spy would be both faster and more accurate than Sharp's own RDS. Maybe I'm not understanding what RDSOutput is supposed to do. It also seems slower to decode than SDR Sharp's RDS.

Do I still need to get MPX Output plugin working for some reason?

Thanks. Real progress compared to where I was before!

**Comment by veso266** [comment]
RDS Output takes RDS Groups from SDR# it then uses ASCII G protocol to send them to RDS Spy, this groups are esentily RDS data before it gets converted to PS, RT, PI, so if you want diferent more acurate results you should try to get MPX Output wokring, it shouldn't be hard
what Virtual Cable solution are you using is it VAC?

**Comment by electro-soma** [comment]
Ok. So I'm not really getting the full benefits of RDS Spy using RDSOutput.

I've used the VB-Cables so far, tried both the HiFi (which everyone recommends) and the standard one. I haven't tried VAC yet. I've had a few experts look over my settings today and they're stumped. What is very odd is the MPX Ouput plugin has some greyed out options. You can see them in this screen shot. I'm sure this is the source of the problem or at least related to it.

Cheers.

![Capture4](https://user-images.githubusercontent.com/52249051/60212385-0bdc2980-9859-11e9-8c0c-946fdb4961a8.JPG)

Here are a few more:

![Capture2](https://user-images.githubusercontent.com/52249051/60212488-45149980-9859-11e9-804e-515f7cdbaa7a.JPG)

![Capture3](https://user-images.githubusercontent.com/52249051/60212500-4cd43e00-9859-11e9-8d2c-8d6db5b9c9df.JPG)

![sounds cfg 1](https://user-images.githubusercontent.com/52249051/60212520-5b225a00-9859-11e9-9a60-a7bcbbcab7f5.JPG)

![sounds cfg 2](https://user-images.githubusercontent.com/52249051/60212528-61183b00-9859-11e9-9ddd-435ec3ef5cf1.JPG)

![sounds listen tab 2](https://user-images.githubusercontent.com/52249051/60212574-7db47300-9859-11e9-8b01-1ef8d8e034fc.JPG)

![sounds listen tab 3](https://user-images.githubusercontent.com/52249051/60212575-7db47300-9859-11e9-9d08-0927a156d228.JPG)

![sounds listen tab](https://user-images.githubusercontent.com/52249051/60212576-7db47300-9859-11e9-8a8c-f50ef8a8a812.JPG)

**Comment by veso266** [comment]
hmm
did you try to send some audio through it with vlc?
maybe use MPX tool to check what comes out

if you go VAC route, here you go: http://downloads.dxing.si/?dir=SA%2FVAC
chose latest one :smile: 
and here are my settings for Line 1:
![VAC](https://user-images.githubusercontent.com/6347325/60213849-a130eb00-9864-11e9-89b3-1650bb135e37.PNG)
Look for Cable 1, the rest I use for some other things :smile:

**Comment by electro-soma** [comment]
Thanks. It's getting late here now and I've been trying to get all this working since 9am! I'll take a look at sending some audio through it tomorrow. Maybe trying someone elses SDRSharp.OutMPX.dll file is worth a try as well. 

Btw, I had to smile when I saw the picture of Toothless and his girlfriend. My daughter has a soft toy Light Fury and she got me to snuggle up to it as she went to sleep earlier. Could do with a sleep myself :-)

**Comment by veso266** [comment]
I can send you my SDR# distro if you want :smile: :http://downloads.dxing.si/download.php?file=SA/sdrsharp-x86.rar

if everything fails you could always uninstall VB Cable and install VAC :smile: 

BTW: do you have a picture of soft toy Light Fury?

**Comment by electro-soma** [comment]
Hi - That would be great. Thanks. Downloaded. I'll take a look in a bit. Been a bit busy today but I intend to start again on RDS Spy later.

I'll get a pic in a bit!

**Comment by electro-soma** [comment]
https://www.buildabear.co.uk/light-fury/427017.html?cgid=stuffed-animals-shop-by-character-how-to-train-your-dragon#start=1

![R0011401](https://user-images.githubusercontent.com/52249051/60280847-a7be7180-98fb-11e9-9003-f6eb2d266010.JPG)

**Comment by veso266** [comment]
oh so cute :smiley:

**Comment by electro-soma** [comment]
It makes noises as well and apparently it is scented with 'rainbows'! Well it certainly smells of something.

Still no luck with RDS Spy. I tried your distro as well. I've spoken with several people who have it working successfully and no one can understand why it doesn't work. Most people have suggested installing Windows 7 or 10 and trying again. I may well do that as I only want Windows for the SDR software anyway.

**Comment by veso266** [comment]
maybe uninstall VB Cable first
then install VAC and try again?

its easier than installing windows 10 :smile: 

its wierd as it should show some buffers like this
![MPX](https://user-images.githubusercontent.com/6347325/60294185-182bb980-9921-11e9-8650-bb114c4760c0.PNG)

what about if you pipe audio with VLC into Cable Output (not the HIFI one) and see what comes out with MPX Tool

BTW: if you want you can have a listen to my AirSpy: https://www.globaltuners.com/receiver/1545-Ljubljana-AirSpy-R2

Slovenija is quite interesting place for DXing (can get all the neighbouring countries + BiH :smile: )

BTW2: Maybe get your Light Fury a Night Fury so she wouldn't be alone :smile: :smiley:

**Comment by electro-soma** [comment]
I'll try the VAC driver. My soundcard dosn't support 192 khz sampling. Does the VAC driver support that? I get confused with these Windows drivers.

Ok. I've installed VLC. How do I pipe audio from there in to the MPX Tool? Is the Tool different to the plugin?

The Airspy looks nice. I've quickly gone off my RTL SDR v3. It's ok for an introduction to SDR but you quickly find the weaknesses of the RTL. I may look at getting the RSP1A. They're easily available here in the UK and the price is good.

I recently got into FM DXing and E Skip/Tropo. We had some Tropo today from Germany. No antenna on the roof so I'm using a portable dipole at the moment for the SDR and my portables.

I think Light Fury and Toothless will be reunited at Christmas!

**Comment by veso266** [comment]
VAC supports 192khz as its a virtual driver it does not depend on DAC/ADC
![MPX2](https://user-images.githubusercontent.com/6347325/60335900-37692c00-999f-11e9-830f-a6c5e0a2efc9.PNG)
Sound->Sound Device-> Line 1

your MPX should look like this
![MPX3](https://user-images.githubusercontent.com/6347325/60335944-55369100-999f-11e9-86bc-6e3546bf70e1.PNG)

MPXTool can also decode stereo and here is how you set it up
![MPXTool1](https://user-images.githubusercontent.com/6347325/60336073-a5adee80-999f-11e9-85f3-a80cfaaaa0e9.PNG)
![MPXTool2](https://user-images.githubusercontent.com/6347325/60336079-a8a8df00-999f-11e9-9d86-ed9b6d014694.PNG)

so try to pipe some audio and see how it looks like


if you only do FM DX you should get AirSpy HF+ Discover (I am waiting for mein): https://www.itead.cc/airspy-hf-discovery.html
it should be the same as my first real DX reciever
![20190628_122936](https://user-images.githubusercontent.com/6347325/60336713-67193380-99a1-11e9-95dd-af9c8537096c.jpg)

![20190628_123157](https://user-images.githubusercontent.com/6347325/60336721-6b455100-99a1-11e9-9352-89e19db27be2.jpg)
got it one year before her :smile: 

still missing a way to computer control my rotator (but once I get a reciever capable of replacing Sony (too afraid to Kondrad Mod it :cry: )) I will buy myself something to do it

BTW: This will be the best christmas for both of them :smile:

**Comment by electro-soma** [comment]
Thanks. I've looked at your screenshots and I'm not really sure what I'm doing with the setup. I need a bit more info. Sorry. The first thing that happened when I opened MPX Tool is I get a registry error about insufficient privileges.  Sigh. Anyway it does open. So I'm testing to see if I can pipe audio from VLC to MPX Tool? I've selected Line 1 in the Audio Device menu in VLC. I'm not sure what I'm doing next.

I'm unsure what MPX Tool is for. Is it necessary for RDS Spy playback with the MPX Output plugin?  I'm a long time Mac user so all this stuff is a bit alien to me! 

You have a very nice setup there. Looks like you're up in the attic or roofspace. I wondered how people rotate their antennas. You can do it remotely?

**Comment by veso266** [comment]
Whopsy gues I am an idiot :smile: 
I forgot to tell you how to install MPXTool :smile: 
first download setup: http://downloads.dxing.si/download.php?file=SA/MPXTool/mpxtool_full_setup.exe
then download its update: http://downloads.dxing.si/download.php?file=SA/MPXTool/MpxTool.2.10.03.DXSW.zip

then run the setup and install it
it should install it in here: "C:\Program Files (x86)\mpxtool"

then go here: C:\Program Files (x86)\mpxtool
and copy everything from MpxTool.2.10.03.DXSW.zip into there (replacing existing files)
then run DXSW.reg (right click and run as admin to get priviligies)

then run it again (MPXTool) (it should work)

then go in its input tab and select the sound device you selected in VLC (one you are piping audio through)

then hit Live, it should display something if any audio is comming through




MPXTool is an analyzer it will show you if MPX Stream is MPX and if Stereo + RDS can be extraxted from it (it also decodes CCIR Stereo) by RDS Spy

BTW: I am using my Yaesu G-8000 DXA to rotate the antena (but don't yet have the box that allows it to be connected to my PC)

**Comment by electro-soma** [comment]
Thanks. That's a great help. All seems to be working ok on that front.

Pretty much given up hope of getting RDS Spy working with MPXoutput. One thing I did notice yesterday, the MPX plugin very briefly flickered into life and the use buffers and lost buffers started working. This didn't last long and hasn't kicked into life again. I also noticed the number of lost buffers was very high. I wonder if this MacBook doesn't meet the requirements this plugin demands.

I've looked at getting RDS Spy and the RTL working with HDSDR but that hasn't gone well either!

![mpx](https://user-images.githubusercontent.com/52249051/60385539-11688800-9a82-11e9-901b-19c57b3a07ee.JPG)

**Comment by veso266** [comment]
You can launch MME repeater and listen to audio

MPXTool shows audio fine
Its not MPX so its fine

Did you set your cable according to the screenshot?

**Comment by electro-soma** [comment]
Well would you believe it. I must have played around with every setting possible. Then I thought to myself let's see what happens if I drop the sample rate from 1.8 to 1.4. This happened!

I apologise for wasting your time. But if you hadn't replied to my issue I would probably have already given up. So you can take the credit! 

![rds spy working](https://user-images.githubusercontent.com/52249051/60385775-37dbf280-9a85-11e9-80ba-7e0f4f27ff81.JPG)

**Comment by veso266** [comment]
You never did/will waste my time :smile:
It was fun to be usefull for once

And i am glad you got it working (Would never though that dropping the sample rate would help)

So mayge buy yourself Airspy HF+ Discover it will serve you better than RSP1

You could also put your Node up on GlobalTuners would love to try it :smile:

So take care, have fun, reunite Light Furry with Totless and hope you get many interesting DX catches :smile:

**Comment by electro-soma** [comment]
Yes it's quite often the obscure settings you'd never think would make things work. It would seem MPXoutput won't run unless it has enough resources. So dropping the sample rate gave it some headroom. 

I will certainly take a look at the Airspy HF + Discover.

I'll look into GlobalTuners. I'm sure you'd have fun listening to the locals but don't expect anything DX worthy with the little whip aerial!

I've uploaded a few videos of the recent Tropo catches on my portables. https://www.youtube.com/user/stellablade/videos

Latest one from last night.

https://youtu.be/0ob9mPDW68A
